import tempfile
import unittest
from pathlib import Path

from topik_sim.hangul_guide import guide
from topik_sim.library import import_pack
from topik_sim.lookup import search_library
from topik_sim.numbers import cheat_sheet
from topik_sim.tts import TTSConfig
from topik_sim.ui import ansi
from topik_sim.ui.shell import GRAMMAR_LEGEND, Shell
from topik_sim.web.app import WebApp

ROOT = Path(__file__).resolve().parents[1]
SAMPLE_PACK = ROOT / "examples" / "content" / "topik_i_mini_pack.json"


class HangulGuideTests(unittest.TestCase):
    def test_guide_is_complete_and_composes_real_syllables(self):
        data = guide()
        self.assertEqual(len(data["consonants"]), 14)
        self.assertEqual(len(data["tense_consonants"]), 5)
        self.assertEqual(len(data["vowels"]), 10)
        self.assertTrue(data["walkthroughs"])
        self.assertIn("받침", data["batchim"])
        # The practice grid is generated by the real composer: ㄱ + ㅏ = 가.
        self.assertEqual(data["syllable_grid"]["rows"][0][0], "가")
        self.assertEqual(data["syllable_grid"]["vowels"][0], "ㅏ")


class NumbersCheatSheetTests(unittest.TestCase):
    def test_tables_come_from_the_graders_converters(self):
        sheet = cheat_sheet()
        self.assertEqual(sheet["sino"][0], {"n": 1, "reading": "일"})
        self.assertEqual(sheet["sino"][-1], {"n": 10000, "reading": "만"})
        native_one = sheet["native"][0]
        self.assertEqual((native_one["reading"], native_one["counter_form"]), ("하나", "한"))
        self.assertTrue(any(row["counter"] == "개" for row in sheet["counters"]))
        self.assertTrue(any(row["system"] == "Native" for row in sheet["usage"]))


class LookupTests(unittest.TestCase):
    def setUp(self):
        self._temp = tempfile.TemporaryDirectory()
        self.library = Path(self._temp.name) / "library"
        import_pack(SAMPLE_PACK, self.library)

    def tearDown(self):
        self._temp.cleanup()

    def test_finds_by_korean_and_english_with_sources(self):
        by_korean = search_library("학생", self.library)  # not taught in mini pack
        self.assertEqual(by_korean["vocabulary"], [])
        by_english = search_library("weather", self.library)
        self.assertEqual(by_english["vocabulary"][0]["ko"], "날씨")
        self.assertEqual(by_english["vocabulary"][0]["pack_id"], "topik-i-mini-pack")
        grammar = search_library("에서", self.library)
        self.assertTrue(any(p["pattern"] == "N에서" for p in grammar["grammar"]))

    def test_blank_query_returns_nothing(self):
        self.assertEqual(search_library("  ", self.library), {"vocabulary": [], "grammar": []})


class StubPrefetcher:
    def warm(self, *args, **kwargs):
        return None

    def close(self):
        return None


class OnrampShellTests(unittest.TestCase):
    def setUp(self):
        ansi.set_color_enabled(False)
        self._temp = tempfile.TemporaryDirectory()
        self.temp_dir = Path(self._temp.name)
        import_pack(SAMPLE_PACK, self.temp_dir / "library")

    def tearDown(self):
        ansi.set_color_enabled(None)
        self._temp.cleanup()

    def make_shell(self):
        output = []
        shell = Shell(
            library_dir=self.temp_dir / "library",
            attempt_dir=self.temp_dir / "attempts",
            tts_config=TTSConfig(output_dir=self.temp_dir / "audio"),
            output=output.append,
            prefetcher=StubPrefetcher(),
            audio_enabled=False,
            flashcard_seed=0,
        )
        return shell, output

    def test_hangul_prints_letters_and_walkthroughs(self):
        shell, output = self.make_shell()
        shell.handle_line("/hangul")
        text = "\n".join(output)
        for token in ("기역", "이응", "받침", "학생", "hak-saeng", "가"):
            self.assertIn(token, text)

    def test_numbers_learn_prints_both_systems(self):
        shell, output = self.make_shell()
        shell.handle_line("/numbers learn")
        text = "\n".join(output)
        self.assertIn("하나", text)
        self.assertIn("일", text)
        self.assertIn("스무 살", text)
        self.assertNotEqual(shell.state, "typing")  # learn shows tables, no drill

    def test_lookup_command_and_empty_result_message(self):
        shell, output = self.make_shell()
        shell.handle_line("/lookup weather")
        self.assertIn("날씨", "\n".join(output))
        output.clear()
        shell.handle_line("/lookup 없는말임")
        self.assertIn("Nothing taught", "\n".join(output))
        output.clear()
        shell.handle_line("/lookup")
        self.assertIn("Usage:", "\n".join(output))

    def test_grammar_cards_show_the_pattern_legend(self):
        shell, output = self.make_shell()
        shell.handle_line("/grammar 1")
        self.assertIn(GRAMMAR_LEGEND, "\n".join(output))
        shell.handle_line("/pause")

    def test_homework_shows_legend_when_pattern_items_exist(self):
        shell, output = self.make_shell()
        shell.handle_line("/homework topik-i-mini-pack 1")
        self.assertIn(GRAMMAR_LEGEND, "\n".join(output))
        shell.handle_line("/pause")

    def test_replay_slow_without_audio_reports_cleanly(self):
        shell, output = self.make_shell()
        shell.handle_line("/replay slow")
        self.assertIn("No question audio", "\n".join(output))


class OnrampWebTests(unittest.TestCase):
    def setUp(self):
        self._temp = tempfile.TemporaryDirectory()
        self.temp_dir = Path(self._temp.name)
        import_pack(SAMPLE_PACK, self.temp_dir / "library")

    def tearDown(self):
        self._temp.cleanup()

    def test_hangul_lookup_and_numbers_guide_endpoints(self):
        app = WebApp(library_dir=self.temp_dir / "library",
                     attempt_dir=self.temp_dir / "attempts",
                     tts_config=TTSConfig(output_dir=self.temp_dir / "audio"),
                     audio_enabled=False, seed=0)
        status, hangul = app.handle("GET", "/api/hangul")
        self.assertEqual(status, 200)
        self.assertEqual(len(hangul["consonants"]), 14)
        status, lookup = app.handle("GET", "/api/lookup", query={"q": "weather"})
        self.assertEqual(lookup["vocabulary"][0]["ko"], "날씨")
        status, sheet = app.handle("GET", "/api/numbers/guide")
        self.assertEqual(sheet["sino"][0]["reading"], "일")

    def test_slow_audio_synthesizes_at_three_quarter_speed(self):
        speeds = []

        def synth(text, config):
            speeds.append(config.speed)
            path = self.temp_dir / "fake.wav"
            path.write_bytes(b"RIFFfake")
            return path

        app = WebApp(library_dir=self.temp_dir / "library",
                     attempt_dir=self.temp_dir / "attempts",
                     tts_config=TTSConfig(output_dir=self.temp_dir / "audio"),
                     audio_enabled=True, seed=0, synthesizer=synth)
        app.handle("GET", "/api/say", query={"text": "안녕"})
        app.handle("GET", "/api/say", query={"text": "안녕", "slow": "1"})
        self.assertEqual(speeds[0], 1.0)
        self.assertAlmostEqual(speeds[1], 0.75)


if __name__ == "__main__":
    unittest.main()
